package org.gfg.JBDL64DBConnectivity.services;

import jakarta.transaction.Transactional;
import org.gfg.JBDL64DBConnectivity.CustomException;
import org.gfg.JBDL64DBConnectivity.Person;
import org.gfg.JBDL64DBConnectivity.model.MyPerson;
import org.gfg.JBDL64DBConnectivity.repositories.MyPersonRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import java.sql.SQLException;
import java.util.List;
import org.gfg.JBDL64DBConnectivity.repositories.IPerson;
@Service
public class PersonService {

    int count  = 1;

    @Autowired
    @Qualifier("personRepository")
    private IPerson iPerson;

    @Autowired
    private MyPersonRepository myPersonRepository;

    public List<Person> getAllPerson() throws SQLException {
        return iPerson.getAllPerson();
    }

    @Transactional(rollbackOn = {CustomException.class})
    public boolean insertPerson(Person person) throws SQLException, CustomException {

        MyPerson myPerson = new MyPerson(person.getName()); // id can be generated by backend
        MyPerson p =  myPersonRepository.save(myPerson);

        if(p.getFirstName().equalsIgnoreCase("rachel")){
            throw new CustomException("not valid");
        }
        return true;
    }

    public int updatePerson(String name, Integer id) {
        try {
            return iPerson.updatePerson(name, id);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    // business logic come under service
    // interaction between third parties
    // interaction with db
}
